# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\uipython\pyqtex\pyqtdb\crud.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, scaleRate):
        self.font = QtGui.QFont()
        self.font.setFamily("黑体")
        self.font.setPointSize(5 * scaleRate)
        MainWindow.setFont(self.font)
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setFixedSize(690 * scaleRate, 680 * scaleRate)
        MainWindow.setWindowIcon(QtGui.QIcon('./truck.ico'))
        #MainWindow.resize(690 * scaleRate, 690 * scaleRate)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateBox = QtWidgets.QGroupBox(self.centralwidget)
        self.dateBox.setGeometry(QtCore.QRect(10 * scaleRate, 10 * scaleRate, 671 * scaleRate, 70 * scaleRate))
        self.dateBox.setObjectName("dateBox")
        self.monthControl = QtWidgets.QDateEdit(self.dateBox)
        self.monthControl.setGeometry(QtCore.QRect(20 * scaleRate, 32 * scaleRate, 411 * scaleRate, 22 * scaleRate))
        self.monthControl.setObjectName("monthControl")
        self.monthControl.setDisplayFormat("yyyy-MM")
        self.monthControl.setDate(QtCore.QDate(datetime.date.today().year, datetime.date.today().month, datetime.date.today().day))
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10 * scaleRate, 90 * scaleRate, 671 * scaleRate, 261 * scaleRate))
        self.groupBox.setObjectName("groupBox")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(580 * scaleRate, 30 * scaleRate, 70 * scaleRate, 30 * scaleRate))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20 * scaleRate, 30 * scaleRate, 47 * scaleRate, 13 * scaleRate))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QComboBox(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20 * scaleRate, 50 * scaleRate, 230 * scaleRate, 20 * scaleRate))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20 * scaleRate, 80 * scaleRate, 47 * scaleRate, 13 * scaleRate))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QComboBox(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(20 * scaleRate, 100 * scaleRate, 230 * scaleRate, 20 * scaleRate))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20 * scaleRate, 130 * scaleRate, 47 * scaleRate, 13 * scaleRate))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(20 * scaleRate, 150 * scaleRate, 230 * scaleRate, 20 * scaleRate))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20 * scaleRate, 190 * scaleRate, 120 * scaleRate, 13 * scaleRate))
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(20 * scaleRate, 210 * scaleRate, 230 * scaleRate, 22 * scaleRate))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDisplayFormat("dd")
        self.dateEdit.setDate(QtCore.QDate(datetime.date.today().year, datetime.date.today().month, datetime.date.today().day))

        self.label_count = QtWidgets.QLabel(self.groupBox)
        self.label_count.setGeometry(QtCore.QRect(260 * scaleRate, 80 * scaleRate, 120 * scaleRate, 13 * scaleRate))
        self.label_count.setObjectName("label_count")
        self.lineEdit_count = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_count.setGeometry(QtCore.QRect(260 * scaleRate, 100 * scaleRate, 230 * scaleRate, 20 * scaleRate))
        self.lineEdit_count.setObjectName("lineEdit_count")

        self.label_weight = QtWidgets.QLabel(self.groupBox)
        self.label_weight.setGeometry(QtCore.QRect(260 * scaleRate, 130 * scaleRate, 120 * scaleRate, 13 * scaleRate))
        self.label_weight.setObjectName("label_weight")
        self.lineEdit_weight = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_weight.setGeometry(QtCore.QRect(260 * scaleRate, 150 * scaleRate, 230 * scaleRate, 20 * scaleRate))
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.label_price = QtWidgets.QLabel(self.groupBox)
        self.label_price.setGeometry(QtCore.QRect(260 * scaleRate, 190 * scaleRate, 120 * scaleRate, 13 * scaleRate))
        self.label_price.setObjectName("label_price")
        self.lineEdit_price = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_price.setGeometry(QtCore.QRect(260 * scaleRate, 210 * scaleRate, 230 * scaleRate, 20 * scaleRate))
        self.lineEdit_price.setObjectName("lineEdit_price")

        self.label_earn = QtWidgets.QLabel(self.groupBox)
        self.label_earn.setGeometry(QtCore.QRect(510 * scaleRate, 130 * scaleRate, 120 * scaleRate, 13 * scaleRate))
        self.label_earn.setObjectName("label_earn")
        self.lineEdit_earn = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_earn.setGeometry(QtCore.QRect(510 * scaleRate, 150 * scaleRate, 150 * scaleRate, 20 * scaleRate))
        self.lineEdit_earn.setObjectName("lineEdit_earn")
        self.label_total = QtWidgets.QLabel(self.groupBox)
        self.label_total.setGeometry(QtCore.QRect(510 * scaleRate, 190 * scaleRate, 120 * scaleRate, 13 * scaleRate))
        self.label_total.setObjectName("label_total")
        self.lineEdit_total = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_total.setGeometry(QtCore.QRect(510 * scaleRate, 210 * scaleRate, 150 * scaleRate, 20 * scaleRate))
        self.lineEdit_total.setObjectName("lineEdit_total")


        self.tableWidget = QtWidgets.QTableView(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10 * scaleRate, 360 * scaleRate, 671 * scaleRate, 261 * scaleRate))
        self.tableWidget.setObjectName("tableWidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10 * scaleRate, 620 * scaleRate, 671 * scaleRate, 41 * scaleRate))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0 * scaleRate, 0 * scaleRate, 669 * scaleRate, 39 * scaleRate))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(60 * scaleRate, 5 * scaleRate, 75 * scaleRate, 23 * scaleRate))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(320 * scaleRate, 5 * scaleRate, 100 * scaleRate, 23 * scaleRate))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(180 * scaleRate, 5 * scaleRate, 75 * scaleRate, 23 * scaleRate))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(460 * scaleRate, 5 * scaleRate, 100 * scaleRate, 23 * scaleRate))
        self.pushButton_4.setObjectName("pushButton_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "物流记录系统"))
        self.groupBox.setTitle(_translate("MainWindow", "数据"))
        self.dateBox.setTitle(_translate("MainWindow", "月份"))
        self.label.setText(_translate("MainWindow", "出发地"))
        self.label_2.setText(_translate("MainWindow", "目的地"))
        self.label_3.setText(_translate("MainWindow", "品名"))
        self.label_4.setText(_translate("MainWindow", "这个月的第几天"))
        self.label_count.setText(_translate("MainWindow", "数量(件)"))
        self.label_weight.setText(_translate("MainWindow", "重量(KG)"))
        self.label_price.setText(_translate("MainWindow", "单价"))
        self.label_total.setText(_translate("MainWindow", "总重(吨)"))
        self.label_earn.setText(_translate("MainWindow", "金额"))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.pushButton_2.setText(_translate("MainWindow", "编辑地点"))
        self.pushButton_3.setText(_translate("MainWindow", "删除"))
        self.pushButton_4.setText(_translate("MainWindow", "导出 Excel"))

